### PR TITLE
Moved "types": "./dist/index.d.ts" into package.json

### PR DESCRIPTION
**Pull request by Semanual**
This solves the TypeScript issue `The 'react-hydration-provider' library may need to update its package.json or typings.`, as explained [here](https://stackoverflow.com/a/76212193).

### CODE REVIEW

**Comment by traviswimer** [comment]
Hey, thanks for the PR!

I think the original `types` property should still be included as a fallback in addition to the one you added though. That seems to be what is suggested in [Typescript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing):

```json
{
    "name": "my-package",
    "type": "module",
    "exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": {
                // Where TypeScript will look.
                "types": "./types/esm/index.d.ts",
                // Where Node.js will look.
                "default": "./esm/index.js"
            },
            // Entry-point for `require("my-package")` in CJS
            "require": {
                // Where TypeScript will look.
                "types": "./types/commonjs/index.d.cts",
                // Where Node.js will look.
                "default": "./commonjs/index.cjs"
            },
        }
    },
    // Fall-back for older versions of TypeScript
    "types": "./types/index.d.ts",
    // CJS fall-back for older versions of Node.js
    "main": "./commonjs/index.cjs"
}
```
Would you mind updating that?

**Comment by Semanual** [comment]
Sure, no problem! I removed because I understood that if `exports` exists, the old `types` key would be ignored.

**Comment by Semanual** [comment]
Following the docs pattern, I used `./dist/index.d.ts` instead of `dist/index.d.ts`

**Comment by traviswimer** [comment]
@Semanual Awesome, thanks! I'll publish a new release soon.

**Pull request merged**
